name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_and_lint:
    name: build_test_and_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Toolchain
        run: rustup update stable && rustup default stable

      - name: Check Crate
        run: cargo check --verbose

      - name: Test and Calculate Coverage
        run: |
          cargo test --all --verbose
          cargo install cargo-tarpaulin && cargo tarpaulin --all

      - name: Run "Hello World"
        run: cargo run -- bf-programs/hello-world.bf > hello-world.txt

      - name: Run primes program (extensible)
        run: cargo run -- -c 1 -e bf-programs/primes.bf > primes.txt

      - name: Run cell-width program
        run: cargo run -- bf-programs/cell-width.bf > cell-width.txt

      - name: Collect artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: *.txt
